//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotes.Logic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSharedGroup
    {
        public int FileSharedGroupId { get; set; }
        public int FileId { get; set; }
        public int GroupId { get; set; }
        public int SemesterSubjectId { get; set; }
    
        public virtual File File { get; set; }
        public virtual Group Group { get; set; }
        public virtual SemesterSubject SemesterSubject { get; set; }
    }
}
