//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotesDal.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSemester
    {
        public GroupSemester()
        {
            this.GroupUser = new HashSet<GroupUser>();
        }
    
        public int GroupSemesterId { get; set; }
        public int GroupId { get; set; }
        public int SemesterId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual ICollection<GroupUser> GroupUser { get; set; }
    }
}
