//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotes.Logic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Grade = new HashSet<Grade>();
            this.UserVisitedSchool = new HashSet<UserVisitedSchool>();
        }
    
        public int SchoolId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual ICollection<UserVisitedSchool> UserVisitedSchool { get; set; }
    }
}
