//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotes.Logic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.GroupSemester = new HashSet<GroupSemester>();
            this.SemesterSubject = new HashSet<SemesterSubject>();
        }
    
        public int SemesterId { get; set; }
        public int SemesterNumber { get; set; }
        public int StudySubjectId { get; set; }
    
        public virtual ICollection<GroupSemester> GroupSemester { get; set; }
        public virtual StudySubject StudySubject { get; set; }
        public virtual ICollection<SemesterSubject> SemesterSubject { get; set; }
    }
}
