//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotes.Logic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterSubject
    {
        public SemesterSubject()
        {
            this.FileSharedGroup = new HashSet<FileSharedGroup>();
        }
    
        public int SemesterSubjectId { get; set; }
        public string Name { get; set; }
        public int SemesterId { get; set; }
    
        public virtual ICollection<FileSharedGroup> FileSharedGroup { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
