//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotes.Logic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterUser
    {
        public int SemesterUserId { get; set; }
        public int SemesterId { get; set; }
        public int UserId { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual User User { get; set; }
    }
}
