//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotesDal.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudySubject
    {
        public StudySubject()
        {
            this.Semester = new HashSet<Semester>();
        }
    
        public int StudySubjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int GradeId { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual ICollection<Semester> Semester { get; set; }
    }
}
