//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotes.Logic.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class robson081192_StudentNotesDBEntities : DbContext
    {
        public robson081192_StudentNotesDBEntities()
            : base("name=robson081192_StudentNotesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<FileSharedGroup> FileSharedGroup { get; set; }
        public virtual DbSet<FileTagPattern> FileTagPattern { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupSemester> GroupSemester { get; set; }
        public virtual DbSet<GroupUser> GroupUser { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<SemesterSubject> SemesterSubject { get; set; }
        public virtual DbSet<StudySubject> StudySubject { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserSharedFile> UserSharedFile { get; set; }
        public virtual DbSet<UserVisitedSchool> UserVisitedSchool { get; set; }
    }
}
