//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotesDal.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVisitedSchool
    {
        public int UserVisitedSchoolId { get; set; }
        public int UserId { get; set; }
        public int SchoolId { get; set; }
    
        public virtual School School { get; set; }
        public virtual User User { get; set; }
    }
}
