//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotesDal.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.File = new HashSet<File>();
            this.Group = new HashSet<Group>();
            this.GroupUser = new HashSet<GroupUser>();
            this.UserSharedFile = new HashSet<UserSharedFile>();
            this.UserVisitedSchool = new HashSet<UserVisitedSchool>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<File> File { get; set; }
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<GroupUser> GroupUser { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserSharedFile> UserSharedFile { get; set; }
        public virtual ICollection<UserVisitedSchool> UserVisitedSchool { get; set; }
    }
}
